---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "manifest_integrity"
description: Check the data integrity of a set of genomic files, listed by their manifest.
keywords:
  - genomics
  - data integrity
  - ensembl
  - genomio
tools:
  - "manifest":
      description: "Nextflow modules for Ensembl genomio manifest"
      homepage: "https://github.com/Ensembl/nextflow_modules"
      # documentation: ""
      # tool_dev_url: ""
      # doi: ""
      licence: "Apache License 2.0"

input:
  - meta:
      type: map
      description: |
        Groovy Map containing meta information
        e.g. `[ id:'accession1' ]`
  
  - manifest_files:
      type: file
      description: Set of genomics files
      pattern: "*.{gff3,fasta,json}"

output:
  - meta:
      type: map
      description: |
        Groovy Map containing meta information
        e.g. `[ id:'accession1' ]`
  
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"

  - all_files:
      type: file
      description: All files used as entry.
      pattern: "*.{gff3,fasta,json}"

  - error_log:
      type: file
      description: Integrity error log if it failed.
      pattern: "integrity.out"

authors:
  - "ensembl-dev@ebi.ac.uk"
maintainers:
  - "ensembl-dev@ebi.ac.uk"
