---
name: "manifest_integrity"
description: >
  Check the data integrity of a set of genomic files, listed by their manifest.
keywords:
  - ensembl
  - genomics
  - genomio
  - integrity
  - validation

tools:
  manifest:
    description: "Nextflow modules for genomic data file manifest comparison/checking"
    homepage: "https://github.com/Ensembl/nextflow_modules"
    license: ["Apache License version 2.0"]
    identifier: ""

input:
  - name: meta
    type: map
    description: "Groovy Map containing meta information, e.g. `[ id:'accession1' ]`"

  - name: manifest_files
    type: file
    description: "Set of genomic data files"
    pattern: "*.{gff3,fasta,json}"

output:
  - name: all_files_meta
    type: map
    description: "Groovy Map containing meta information, e.g. `[ id:'accession1' ]`"

  - name: all_files
    type: file
    description: "All files used as entry"
    pattern: "*.{gff3,fasta,json}"
    includeInputs: true

  - name: error_log_meta
    type: map
    description: "Groovy Map containing meta information, e.g. `[ id:'accession1' ]`"

  - name: integrity_file
    type: file
    description: "Captures potential errors detected during integrity check"
    pattern: "integrity.out"

  - name: versions
    type: file
    description: "File containing module software versions"
    pattern: "versions.yml"

authors:
  - "@ensembl-dev"
maintainers:
  - "@ensembl-dev"
