---
name: "manifest_maker"
description: >
  Generate a manifest and validate its JSON schema using provided input
  files and metadata.
keywords:
  - ensembl
  - genomics
  - genomio
  - integrity
  - validation

tools:
  manifest_maker:
    description: "Nextflow modules for genomic data file manifest comparison/checking."
    homepage: "https://github.com/Ensembl/nextflow_modules"
    license: ["Apache License version 2.0"]
    identifier: ""

input:
  - name: meta
    type: map
    description: >
      Groovy Map containing meta information, e.g. `[ accession:'accession01' ]`
  - name: file_name
    type: file
    description: "Input file to validate."

output:
  - name: versions
    type: file
    description: "File containing information on module software version."
    pattern: "versions.yml"

authors:
  - "ensembl-dev@ebi.ac.uk"
maintainers:
  - "ensembl-dev@ebi.ac.uk"
