# See the NOTICE file distributed with this work for additional information
# regarding copyright ownership.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: "schema_json"
description: Validate the schema for JSON files
keywords:
  - validate
  - JSON
  - schema
tools:
  - "Schema":
      description: "Nextflow modules for Ensembl pipelines"
      homepage: "https://github.com/Ensembl/nextflow_modules"
      # documentation: ""
      # tool_dev_url: ""
      # doi: ""
      licence: "Apache License 2.0"
input:
  # Only when we have meta
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. `[ id:'sample1', single_end:false ]`
  
  - json:
      type: file
      description: JSON file to validate
      pattern: "*.{json}"

output:
  # Only when we have meta
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. `[ id:'sample1', single_end:false ]`
  - versions:
      type: file
      description: File containing ensembl-genomio versions
      pattern: "versions.yml"
  - json:
      type: file
      description: verified_json file
      pattern: "*.{json}"

authors:
  - "ensembl-dev@ebi.ac.uk"
maintainers:
  - "ensembl-dev@ebi.ac.uk"