---
name: "metadata_genomesummary"
description: Extract genome meta info from an NCBI datasets-cli 'genome summary' JSON.
keywords:
  - container
  - docker
  - datasets
  - ensembl-genomio
  - genome
  - metadata

tools:
  metadata:
    description: Modules which function to generate, fetch or otherwise work \
      with metadata curation or preparation.
    homepage: "https://github.com/Ensembl/nextflow_modules"
    license: ["Apache License version 2.0"]

input:
  - name: accession
    type: map
    description: Meta map including sequence accession.

  - name: input_query
    type: file
    description: Input query to parse an NCBI genome summary JSON
    pattern: "*-query.json"

  - name: genome_summary_json
    type: file
    description: |
      A genome summary JSON file downloaded via datasets-cli (NCBI)
    pattern: "*.json"

output:
  - name: meta
    type: map
    description: Meta map including sequence accession.

  - name: meta_json
    type: file
    description: Genome metadata queried from JSON.
    pattern: "*-meta.json"

  - name: versions
    type: file
    description: File containing software versions
    pattern: "versions.yml"

authors:
  - "ensembl-dev@ebi.ac.uk"

maintainers:
  - "ensembl-dev@ebi.ac.uk"
