name: metadata_genomesummary
description: 'Extract genome metadata from an NCBI datasets-cli ''genome summary''
  JSON.

  A structured query JSON is also input and used to extract key metadata.

  '
keywords:
- container
- docker
- datasets
- ensembl-genomio
- genome
- metadata
tools:
- metadata:
    description: Modules which generate, fetch, or otherwise work with metadata curation
      or preparation.
    homepage: https://github.com/Ensembl/nextflow_modules
    licence:
    - Apache License version 2.0
input:
- - meta:
      type: map
      description: Channel element meta.
  - input_query:
      type: file
      description: Input query to parse an NCBI genome summary JSON.
      pattern: '*-query.json'
  - genome_summary_json:
      type: file
      description: 'A genome summary JSON file downloaded via datasets-cli (NCBI),

        containing one or more genome summaries.

        '
      pattern: '*.json'
output:
  meta_json:
  - - meta:
        type: map
        description: "Meta map including sequence accession. Sequence record associated\
          \ with \nNCBI accession (e.g. NC_0-9+, NM_0-9+, NT_0-9+, NP_0-9+)\ne.g.\
          \ [[ accession:'NC_12341']]\n"
    - genome.json:
        type: file
        description: Channel element genome.json.
        pattern: genome.json
  versions:
  - versions.yml:
      type: file
      description: Channel element versions.yml.
      pattern: versions.yml
authors:
- ensembl-dev@ebi.ac.uk
maintainers:
- ensembl-dev@ebi.ac.uk
