---
name: "metadata_amendgenome"
description: >
  Extends genome metadata using input files and validates the output against
  a genome schema.
keywords:
  - amend
  - genome
  - metadata
  - validation

tools:
  metadata_amendgenome:
    description: >
      This module processes genome metadata by incorporating additional
      data from assembly reports and GenBank files, ensuring compliance with the
      genome schema
    homepage: "https://github.com/Ensembl/nextflow_modules"
    license: ["Apache License version 2.0"]
    identifier: ""

input:
  - name: meta
    type: map
    description: >
      Groovy Map containing meta information e.g. `[ accession:'accession01' ]`
  - name: genome_json
    type: file
    description: "JSON file containing genome metadata."
    pattern: "*.json"
  - name: asm_report
    type: file
    description: "Assembly report file with genomic metadata."
    pattern: "*.txt"
  - name: genomic_fna
    type: file
    description: "FASTA file containing genomic sequences."
    pattern: "*.{fna,fasta,fa}"
  - name: genbank_gbff
    type: file
    description: "GenBank file containing genome annotations."
    pattern: "*.{gbff,gb}"

output:
  - name: amended_json
    type: map
    description: >
      Groovy Map containing meta information e.g. `[ accession:'accession01' ]`
  - name: amended_json_file
    type: file
    description: "JSON file containing genome metadata."
    pattern: "*.json"
  - name: versions
    type: file
    description: "File containing information on module software version."
    pattern: "versions.yml"

authors:
  - "@ensembl-dev"
maintainers:
  - "@ensembl-dev"
