name: "download_genbank"
description: Download a single sequence from NCBI GenBank.

keywords:
  - core_database
  - container
  - docker
  - ensembl-genomio
  - genbank
  - genomics

tools:
  - download:
      description:
        "Modules which function to download information or various data from\
        \ externally hosted resources."
      homepage: "https://github.com/Ensembl/nextflow_modules"
      license: ["Apache License version 2.0"]
      identifier: ""

input:
  - - meta: {}
output:
  - gb_sequence:
      - meta:
          type: file
          description: A sequence record outfile in genbank format.
          pattern: "output.gb"
      - output.gb:
          type: file
          description: A sequence record outfile in genbank format.
          pattern: "output.gb"
  - versions:
      - versions.yml:
          type: file
          description: File containing information on module software version
          pattern: "versions.yml"
authors:
  - "ensembl-dev@ebi.ac.uk"
maintainers:
  - "ensembl-dev@ebi.ac.uk"
