---
name: "download_genbank"
description: >
  Download a single sequence from NCBI GenBank.

keywords:
  - core_database
  - container
  - docker
  - ensembl-genomio
  - genbank
  - genomics

tools:
  download:
    description: >
      Modules which function to download information or various data from
      externally hosted resources.
    homepage: "https://github.com/Ensembl/nextflow_modules"
    license: ["Apache License version 2.0"]
    identifier: ""

input:
  - name: meta
    type: map
    description: "Optional meta information about the sequence to download."

output:
  - name: gb_sequence_file
    type: file
    description: "A sequence record outfile in GenBank format"
    pattern: "output.gb"

  - name: gb_sequence_meta
    type: map
    description: "Metadata associated with the downloaded GenBank sequence"

  - name: versions
    type: file
    description: "File containing information on module software version"
    pattern: "versions.yml"

authors:
  - "ensembl-dev@ebi.ac.uk"
maintainers:
  - "ensembl-dev@ebi.ac.uk"
