---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "database_dbfactory"
description: Generate a list of one or more databases plus some associated meta table information.

keywords:
  - core_database
  - python
  - ensembl-genomio

tools:
  - database:
      # documentation: ""
      homepage: "https://github.com/Ensembl/nextflow_modules"
      description: "Modules which function to read or write information from core databases."
      licence: ['Apache License version 2.0']
      # tool_dev_url: ""
      # doi: ""

input:
  - server:
      type: string
      description: "String containing mysql server host,port,user,password e.g. '--host mysql-ens-hostname-1 --port XXXX --user ensro'"
  
  - filter_map:
      type: file
      description: "List of one of more database names to filter all databases using prefix &| dbname_re"

output:
  - dbs_meta_json:
      type: file
      description: "JSON file containing database meta data"

authors:
  - "@ensembl-dev"
maintainers:
  - "@ensembl-dev"
