---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "fasta_dumpfastanuc"
description: Generate a list of one or more databases plus some associated meta table information.

keywords:
  - core_database
  - python
  - ensembl-genomio
  - ensembl-legacy-scripts
  - fasta
  - docker
  - container

tools:
  - database:
      # documentation: ""
      homepage: "https://github.com/Ensembl/nextflow_modules"
      description: "Modules which function to read or write information from core databases."
      licence: ['Apache License version 2.0']
      # tool_dev_url: ""
      # doi: ""

input:
  - host:
      type: string
      description: "String containing mysql server host e.g. '--host mysql-ens-hostname-1'"
  - port:
      type: string
      description: "String containing mysql server port: '--port 1234'"
  - user:
      type: string
      description: "String containing mysql server user,password e.g. '--user ensro'"
  - pass:
      type: string
      description: "String containing mysql server user,password e.g. '--pass XxYyZz'"

output:
  - stdout:
      type: stdout
      description: "Fasta file containing nucleotide sequence(s)."

authors:
  - "@ensembl-dev"
maintainers:
  - "@ensembl-dev"