name: "fasta_split"
description: Split a FASTA file into smaller FASTA files and optionally write an
  AGP file.
keywords:
  - ensembl
  - fasta
  - genomics
  - genomio
  - split
tools:
  - "fasta_split":
      description: "Split FASTA files with ensembl-genomio."
      homepage: "https://github.com/Ensembl/ensembl-genomio"
      licence:
        - "Apache License version 2.0"
      identifier: ""
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing meta information
          e.g. `[ id:'accession1' ]`
    - fasta:
        type: file
        description: FASTA file to split.
        pattern: "*.{fa,fasta,fna}"
        ontologies:
          - edam: "http://edamontology.org/format_1929" # FASTA
    - longest_seq_bp:
        type: integer
        description: Length in base pairs of the longest sequence in the input
          FASTA.
output:
  fastas:
    - - meta:
          type: map
          description: |
            Groovy Map containing meta information
            e.g. `[ id:'accession1' ]`
      - splits/**/*.fa:
          type: file
          description: Split FASTA files.
          pattern: "splits/**/*.fa"
          ontologies:

  agp:
    - - meta:
          type: map
          description: |
            Groovy Map containing meta information
            e.g. `[ id:'accession1' ]`
      - splits/*.agp:
          type: file
          description: Optional AGP file describing split sequence chunks.
          pattern: "splits/*.agp"
          ontologies:
            - edam: "http://edamontology.org/format_3693" # AGP
  versions_fasta_split:
    - - ${task.process}:
          type: string
          description: The name of the process.
      - fasta_split:
          type: string
          description: The name of the tool.
      - "fasta_split --version":
          type: eval
          description: The expression to obtain the version of the tool
topics:
  versions:
    - - ${task.process}:
          type: string
          description: The name of the process.
      - fasta_split:
          type: string
          description: The name of the tool.
      - "fasta_split --version":
          type: eval
          description: The expression to obtain the version of the tool
authors:
  - "ensembl-dev@ebi.ac.uk"
maintainers:
  - "ensembl-dev@ebi.ac.uk"
