name: annotation_dumpanno
description: This module is used to dump the functional annotation of a genome from
  core databases.
keywords:
- container
- core_database
- docker
- ensembl-legacy-scripts
- fasta
tools:
- annotation:
    homepage: https://github.com/Ensembl/nextflow_modules
    description: This module handles all annotation-related interactions with the
      core database, including annotation dumping and processing
    licence:
    - Apache License version 2.0
input:
- db:
    type: map
    description: Channel element db.
output:
  functional_annotation:
  - - db:
        type: map
        description: Channel element db.
    - functional_annotation:
        type: string
        description: Channel element functional_annotation.
    - '*.json':
        type: file
        description: Channel element *.json.
        pattern: '*.json'
  versions:
  - versions.yml:
      type: file
      description: File containing software versions.
      pattern: versions.yml
authors:
- '@ensembl-dev'
maintainers:
- '@ensembl-dev'
