---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "dump_genomestats"
description: A module for dumping core database ......
keywords:
  - core_database
  - python
  - ensembl-genomio
  - json
  - docker
  - container

tools:
  - dump:
      homepage: "https://github.com/Ensembl/nextflow_modules"
      description: "Modules which function to dump various forms of data from a core database."
      licence: ['Apache License version 2.0']

input:
  - host:
      type: string
      description: "String containing mysql server host e.g. '--host mysql-ens-hostname-1'"
  - port:
      type: string
      description: "String containing mysql server port: '--port 1234'"
  - user:
      type: string
      description: "String containing mysql server user,password e.g. '--user ensro'"
  - pass:
      type: string
      description: "String containing mysql server user,password e.g. '--pass XxYyZz'"
  - dbname:
      type: string
      description: "Target database name to dump fasta sequences."

output:
  - stdout:
      type: stdout
      description: "JSON file containing core database statistics (assembly and annotation)."

authors:
  - "@ensembl-dev"
maintainers:
  - "@ensembl-dev"