---
name: "genbank_extractgb"
description: >
  Parse a GenBank file and create cleaned up files, validating generated
  JSON files.

keywords:
  - container
  - database
  - docker
  - ensembl-genomio
  - genbank
  - genomics

tools:
  genbank:
    description: >
      Modules with functions related to working with GenBank data files.
    homepage: "https://github.com/Ensembl/nextflow_modules"
    license: ["Apache License version 2.0"]
    identifier: ""

input:
  - name: meta
    type: map
    description: "Groovy Map containing genome database meta information, e.g. `[ accession:'NC_XXXX.X' ]`"

  - name: gb_file
    type: file
    description: "File path to GenBank formatted input file (*.gb), e.g. `[gb_file('genome.gb')]`"

output:
  - name: genome_meta
    type: file
    description: "Genome metadata (JSON)"
    pattern: "genome.json"

  - name: seq_regions_meta
    type: file
    description: "Sequence region(s) metadata (JSON)"
    pattern: "seq_region.json"

  - name: dna_fasta
    type: file
    description: "Genome nucleotide sequence(s) (FASTA)"
    pattern: "dna.fasta"

  - name: gene_gff
    type: file
    description: "Gene model information (GFF3)"
    pattern: "*.gff"

  - name: pep_fasta
    type: file
    description: "Genome protein-coding gene amino acid sequence(s) (FASTA)"
    pattern: "pep.fasta"

  - name: versions
    type: file
    description: "File containing information on module software version"
    pattern: "versions.yml"

authors:
  - "ensembl-dev@ebi.ac.uk"
maintainers:
  - "ensembl-dev@ebi.ac.uk"
