---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "GFF3_VALIDATION"
description: Check the validation of the GFF3 using gt tools.
keywords:
  - genomics
  - data integrity
  - ensembl
  - genomio
tools:
  - "gff3":
      description: "Nextflow modules for GFF3 validation"
      homepage: "https://github.com/Ensembl/nextflow_modules"
      # documentation: ""
      licence: "Apache License 2.0"

input:
  - meta:
      type: map
      description: |
        Groovy Map containing meta information
        e.g. `[ id:'accession1' ]`
  
  - manifest_files:
      type: file
      description: GFF3 files
      pattern: "*.{gff3}"

output:
  - meta:
      type: map
      description: |
        Groovy Map containing meta information
        e.g. `[ id:'accession1' ]`
  
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"

  - gene_models:
      type: file
      description: All files used as entry
      pattern: "*.{gff3}"

authors:
  - "ensembl-dev@ebi.ac.uk"
maintainers:
  - "ensembl-dev@ebi.ac.uk"
