---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
name: "fasta_dumpfastapeptide"
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.10
  - pip
  - pip:
    - ensembl-genomio=1.5.0