---
name: "fasta_dumpfastapeptide"
description: >
  A module for dumping peptide FASTA sequences from core databases.

keywords:
  - container
  - database
  - docker
  - ensembl-genomio
  - ensembl-legacy-scripts
  - fasta

tools:
  fasta:
    description: >
      Modules which function to facilitate data deposition and retrieval
      of FASTA sequences.
    homepage: "https://github.com/Ensembl/nextflow_modules"
    license: ["Apache License version 2.0"]
    identifier: ""

input:
  - name: db
    type: map
    description: >
      A meta map including 'core database name',
      e.g. [[ db:'genus_species_gca00000000v1_core_110_1', species:'Genus species', ...]]
    pattern: "[a-z]+_[a-z]_gc[af][0-9]v[0-9]+_core_*"

output:
  - name: peptide_fasta_meta
    type: map
    description: >
      Metadata for peptide FASTA sequences, e.g. [ db:'database name', file("*_fasta_pep.fasta") ]

  - name: peptide_fasta_file
    type: file
    description: "Peptide FASTA sequences from the database"
    pattern: "*_fasta_pep.fasta"

  - name: versions
    type: file
    description: "File containing information on module software version"
    pattern: "versions.yml"

authors:
  - "ensembl-dev@ebi.ac.uk"
maintainers:
  - "ensembl-dev@ebi.ac.uk"
