name: Run Linting

on: [push, pull_request]

env:
  NXF_SINGULARITY_CACHEDIR: ${{ github.workspace }}/.singularity
  NXF_SINGULARITY_LIBRARYDIR: ${{ github.workspace }}/.singularity
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  NXF_VER: "25.10.2"
  NXF_SYNTAX_PARSER: "v2"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  nf-core-changes:
    name: Detect changes
    runs-on: ubuntu-latest

    outputs:
      modules: ${{ steps.filter.outputs.modules }}
      subworkflows: ${{ steps.filter.outputs.subworkflows }}

    steps:
      - uses: actions/checkout@v6

      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            modules:
              - 'modules/ensembl/**'
            subworkflows:
              - 'subworkflows/ensembl/**'

  nf-core-lint:
    name: nf-core lint
    runs-on: ubuntu-latest
    needs: nf-core-changes

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - uses: actions/cache@v5
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip

      - uses: nf-core/setup-nextflow@v2

      - name: Install nf-core tools
        run: pip install --upgrade git+https://github.com/nf-core/tools.git@dev

      - name: Lint modules
        if: needs.nf-core-changes.outputs.modules == 'true'
        run: nf-core modules lint

      - name: Lint subworkflows
        if: needs.nf-core-changes.outputs.subworkflows == 'true'
        run: nf-core subworkflows lint