name: Run Linting
on: [push, pull_request]

env:
  NXF_SINGULARITY_CACHEDIR: ${{ github.workspace }}/.singularity
  NXF_SINGULARITY_LIBRARYDIR: ${{ github.workspace }}/.singularity
  # renovate: datasource=github-releases depName=nextflow/nextflow versioning=semver
  NXF_VER: "25.10.2"

jobs:
  nf-core-lint-modules:
    runs-on:
      - runs-on=${{ github.run_id }}-nf-core-lint-modules
      - runner=4cpu-linux-x64
      - image=ubuntu22-full-x64
    name: nf-core lint modules
    needs: nf-core-changes
    if: ${{ needs.nf-core-changes.outputs.modules_files != '[]' }}
    strategy:
      fail-fast: false
      matrix:
        module: ${{ fromJson(needs.nf-core-changes.outputs.modules_files || '[]') }}
    steps:
      - name: Clean workspace
        run: |
          sudo rm -rf ./* || true
          sudo rm -rf ./.* || true
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6
        with:
          python-version: "3.14"

      - uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5
        id: cache-pip
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip
          restore-keys: |
            ${{ runner.os }}-pip

      - name: Install pip
        run: python -m pip install --upgrade pip

      - uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Set up Nextflow
        uses: nf-core/setup-nextflow@v2

      - name: Install nf-core tools development version
        run: python -m pip install --upgrade --force-reinstall git+https://github.com/nf-core/tools.git@dev

      - name: Lint module ${{ matrix.module }}
        run: nf-core modules lint ${{ matrix.module }}

  nf-core-lint-subworkflows:
    runs-on:
      - runs-on=${{ github.run_id }}-nf-core-lint-subworkflows
      - runner=4cpu-linux-x64
      - image=ubuntu22-full-x64
    name: nf-core lint subworkflows
    needs: nf-core-changes
    if: ${{ needs.nf-core-changes.outputs.subworkflows_files != '[]' }}
    strategy:
      fail-fast: false
      matrix:
        subworkflow: ${{ fromJson(needs.nf-core-changes.outputs.subworkflows_files || '[]') }}
    steps:
      - name: Clean workspace
        run: |
          sudo rm -rf ./* || true
          sudo rm -rf ./.* || true
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6
        with:
          python-version: "3.14"

      - name: Set up Nextflow
        uses: nf-core/setup-nextflow@v2

      - name: Install nf-core tools development version
        run: python -m pip install --upgrade --force-reinstall git+https://github.com/nf-core/tools.git@dev

      - name: Lint subworkflow ${{ matrix.subworkflow }}
        run: nf-core subworkflows lint ${{ matrix.subworkflow }}

  confirm-pass-lint:
    runs-on:
      - runs-on=${{ github.run_id }}-confirm-pass-lint
      - runner=2cpu-linux-x64
      - image=ubuntu22-full-x64
    needs: [nf-core-lint-modules, nf-core-lint-subworkflows]
    if: always()
    steps:
      - name: All tests ok
        if: ${{ success() || !contains(needs.*.result, 'failure') }}
        run: exit 0
      - name: One or more tests failed
        if: ${{ contains(needs.*.result, 'failure') }}
        run: exit 1

      - name: debug-print
        if: always()
        run: |
          echo "toJSON(needs) = ${{ toJSON(needs) }}"
          echo "toJSON(needs.*.result) = ${{ toJSON(needs.*.result) }}"